apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web
spec:
  serviceName: "nginx"
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - args:
        - -c
        - while true; do dd if=/dev/urandom of=/usr/share/nginx/html/$(hostname)-random.img count=1024M
          bs=2K; sleep 30; rm -rf /usr/share/nginx/html/*; done
        name: nginx
        command:
          - /bin/sh
        image: busybox:latest
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "storageclass-wekafs-dir-api" # Replace with your StorageClass name
      resources:
        requests:
          storage: 28Gi
