{
 "title": "Weka Clusters",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "Cluster", "query": { "query": "label_values(cluster_name)" } }
  ]
 },
 "panels": [
  { "title": "Cluster-wide info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Alerts Counter",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "weka_cluster_alerts_count{cluster_name=\"$Cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Status",
   "type": "state-timeline",
   "gridPos": { "h": 5, "w": 10, "x": 5, "y": 1 },
   "targets": [
    {
     "expr": "weka_cluster_status{cluster_name=\"$Cluster\"}",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Max Cpu Utilization",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 1 },
   "targets": [
    {
     "expr": "max by(mode) (weka_cpu_utilization_percent{weka_io_cluster_name=\"$Cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Protection Status",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(weka_cluster_protection_level{cluster_name=\"$Cluster\"}) by (num_failures)",
     "legendFormat": "{{num_failures}} Failures"
    }
   ]
  },
  {
   "title": "Protection Status Over Time",
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(weka_cluster_protection_level{cluster_name=\"$Cluster\"}) by (num_failures)",
     "legendFormat": "{{num_failures}} Failures"
    }
   ]
  },
  {
   "title": "Containers",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "weka_cluster_containers_count{cluster_name=~\"$Cluster\", type=\"compute\"}",
     "legendFormat": "{{type}}:{{status}}"
    },
    {
     "expr": "weka_cluster_containers_count{cluster_name=~\"$Cluster\", type=\"drive\"}",
     "legendFormat": "{{type}}:{{status}}"
    }
   ]
  },
  {
   "title": "Cluster drives",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "weka_cluster_drives_count{cluster_name=\"$Cluster\"}",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Processes",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "weka_cluster_processes_count{cluster_name=~\"$Cluster\", type=\"compute\"}",
     "legendFormat": "{{type}}:{{status}}"
    },
    {
     "expr": "weka_cluster_processes_count{cluster_name=~\"$Cluster\", type=\"drive\"}",
     "legendFormat": "{{type}}:{{status}}"
    }
   ]
  },
  {
   "title": "Iops",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "weka_cluster_iops{cluster_name=\"$Cluster\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Cluster Capacities",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "weka_cluster_capacity_bytes{cluster_name=\"$Cluster\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "NIC Data rate per container type",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(mode) (rate(weka_port_rx_bytes_total{weka_io_cluster_name=\"$Cluster\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "weka_cluster_throughput_bytes_per_second{cluster_name=\"$Cluster\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Drive Read/Write Requests/Sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(weka_drive_read_requests_total{weka_io_cluster_name=\"$Cluster\"}[$__rate_interval])) by (weka_io_cluster_name)",
     "legendFormat": "read requests"
    },
    {
     "expr": "sum(rate(weka_drive_write_requests_total{weka_io_cluster_name=\"$Cluster\"}[$__rate_interval])) by (weka_io_cluster_name)",
     "legendFormat": "write requests"
    }
   ]
  },
  {
   "title": "AVG Drive Read/Write Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(\n    rate(weka_drive_read_seconds_total{weka_io_cluster_name=\"$Cluster\"}[$__rate_interval])\n/\nrate(weka_drive_read_requests_total{weka_io_cluster_name=\"$Cluster\"}[$__rate_interval]) > 0\n)",
     "legendFormat": "AVG read"
    },
    {
     "expr": "avg(\n    rate(weka_drive_write_seconds_total{weka_io_cluster_name=\"$Cluster\"}[$__rate_interval])\n/\nrate(weka_drive_write_requests_total{weka_io_cluster_name=\"$Cluster\"}[$__rate_interval]) > 0\n)",
     "legendFormat": "AVG write"
    }
   ]
  },
  {
   "title": "Drive Read/Write Throughput ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(weka_drive_write_bytes_total{weka_io_cluster_name=\"$Cluster\"}[$__rate_interval]))",
     "legendFormat": "write"
    },
    {
     "expr": "sum(rate(weka_drive_read_bytes_total{weka_io_cluster_name=\"$Cluster\"}[$__rate_interval]))",
     "legendFormat": "read"
    }
   ]
  },
  {
   "title": "API Requests Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(weka_api_requests_total{weka_io_cluster_name=~\"$Cluster\"}[$__rate_interval])) by (http_code_group)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Pending IOs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "targets": [
    {
     "expr": "sum(weka_client_pending_ios_count{weka_io_cluster_name=\"$Cluster\"})",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Average Read Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(\n    rate(weka_fs_read_seconds_total{weka_io_cluster_name=\"$Cluster\"}[$__rate_interval])\n/\nrate(weka_fs_read_requests_total{weka_io_cluster_name=\"$Cluster\"}[$__rate_interval]) > 0\n) by (weka_io_cluster_name)",
     "legendFormat": "AVG read"
    }
   ]
  },
  {
   "title": "Average Write Latency ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(\n    rate(weka_fs_write_seconds_total{weka_io_cluster_name=\"$Cluster\"}[$__rate_interval])\n/\nrate(weka_fs_write_requests_total{weka_io_cluster_name=\"$Cluster\"}[$__rate_interval]) > 0\n) by (weka_io_cluster_name)",
     "legendFormat": "AVG write"
    }
   ]
  },
  {
   "title": "Per FS info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 },
   "collapsed": true,
   "panels": [
    {
     "title": "Average Read Latency by FS",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg(\n    rate(weka_fs_read_seconds_total{weka_io_cluster_name=\"$Cluster\"}[$__rate_interval])\n/\nrate(weka_fs_read_requests_total{weka_io_cluster_name=\"$Cluster\"}[$__rate_interval]) > 0\n) by (fs_name)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Average Write Latency by FS",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg(\n    rate(weka_fs_write_seconds_total{weka_io_cluster_name=\"$Cluster\"}[$__rate_interval])\n/\nrate(weka_fs_write_requests_total{weka_io_cluster_name=\"$Cluster\"}[$__rate_interval]) > 0\n) by (fs_name)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "AVG Read Requestes/Sec by FS",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(rate(weka_fs_read_requests_total{weka_io_cluster_name=\"$Cluster\"}[$__rate_interval])) by (fs_name)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "AVG Write Requestes/Sec by FS",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 67 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(rate(weka_fs_write_requests_total{weka_io_cluster_name=\"$Cluster\"}[$__rate_interval])) by (fs_name)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Read Throughput by FS",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 75 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(rate(weka_fs_read_bytes_total{weka_io_cluster_name=\"$Cluster\"}[$__rate_interval])) by (fs_name)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Write Throughput by FS",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 75 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(rate(weka_fs_write_bytes_total{weka_io_cluster_name=\"$Cluster\"}[$__rate_interval])) by (fs_name)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Top Containers Info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pending IOs Per Container",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 100 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "topk(5,max(weka_client_pending_ios_count{weka_io_cluster_name=\"$Cluster\"}) by (container_name)) > 0",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Top Drives info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 },
   "collapsed": true,
   "panels": [
    {
     "title": "Drive Smart Media Errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 260 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "topk(50,weka_drive_smart_media_errors_sample{weka_io_cluster_name=\"$Cluster\"})",
       "legendFormat": "serial - {{serial}}, weka uid - {{weka_uid}}"
      }
     ]
    },
    {
     "title": "Drive Smart Critical Warnings",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 260 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "topk(50,weka_drive_smart_critical_warnings_sample{weka_io_cluster_name=\"$Cluster\"})",
       "legendFormat": "serial - {{serial}}, weka uid - {{weka_uid}}"
      }
     ]
    },
    {
     "title": "Drive Smart Composite Temp",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 300 },
     "targets": [
      {
       "expr": "topk(50,weka_drive_smart_composite_temp{weka_io_cluster_name=\"$Cluster\"})",
       "legendFormat": "serial - {{serial}}, weka uid - {{weka_uid}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Top Processes info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network Received ",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 252 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "topk(10,sum(rate(weka_port_rx_bytes_total{weka_io_cluster_name=\"$Cluster\"}[$__rate_interval])) by (mode,process_id))",
       "legendFormat": "{{mode}} - process {{process_id}}"
      }
     ]
    },
    {
     "title": "Network Transmitted",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 252 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "topk(10,sum(rate(weka_port_tx_bytes_total{weka_io_cluster_name=\"$Cluster\"}[$__rate_interval])) by (mode,process_id))",
       "legendFormat": "{{mode}} - process {{process_id}}"
      }
     ]
    },
    {
     "title": "Drive Read Requests",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 260 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "topk(10,sum(rate(weka_drive_read_requests_total{weka_io_cluster_name=\"$Cluster\"}[$__rate_interval])) by (mode,process_id))",
       "legendFormat": "{{mode}} - process {{process_id}}"
      }
     ]
    },
    {
     "title": "Drive Write Requests",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 260 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "topk(10,sum(rate(weka_drive_write_requests_total{weka_io_cluster_name=\"$Cluster\"}[$__rate_interval])) by (mode,process_id))",
       "legendFormat": "{{mode}} - process {{process_id}}"
      }
     ]
    }
   ]
  }
 ]
}